added v1.x

diff --git a/flapjack/etc/init.d/flapjack b/flapjack/etc/init.d/flapjack
--- a/flapjack/etc/init.d/flapjack
+++ b/flapjack/etc/init.d/flapjack
@@ -17,65 +17,15 @@
 # Boots flapjack (coordinator, processor, notifier, gateways...)
 
 PATH=/opt/flapjack/bin:$PATH
-DAEMON=/opt/flapjack/bin/flapjack
-DAEMON_ARGS=server
-NAME=flapjack
-DESC=flapjack
 
-RUNDIR=/var/run/flapjack
-PIDFILE=$RUNDIR/$NAME.pid
+if ! type flapjack > /dev/null 2>&1; then
+  echo "Error: flapjack isn't in PATH."
+  echo "Refusing to do anything!"
+  exit 1
+fi
 
-test -x $DAEMON || exit 0
+# Evaluate command
+flapjack server $@
 
-set -e
-
-case "$1" in
-  start)
-    echo -n "Starting $DESC: "
-    mkdir -p $RUNDIR
-    touch $PIDFILE
-    chown flapjack:flapjack $RUNDIR $PIDFILE
-    chmod 755 $RUNDIR
-    if start-stop-daemon --start --background --quiet --umask 022 --make-pidfile --pidfile $PIDFILE --chuid flapjack:flapjack --startas $DAEMON --exec $DAEMON -- $DAEMON_ARGS
-    then
-      echo "$NAME."
-    else
-      echo "failed"
-    fi
-    ;;
-
-  stop)
-    echo -n "Stopping $DESC: "
-    if start-stop-daemon --stop --retry TERM/15/KILL/10 --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON
-    then
-      echo "$NAME."
-    else
-      echo "failed"
-    fi
-    rm -f $PIDFILE
-    ;;
-
-  restart|force-reload)
-    ${0} stop
-    ${0} start
-    ;;
-
-  status)
-    echo -n "$DESC is "
-    if start-stop-daemon --status --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
-    then
-      echo "running"
-    else
-      echo "not running"
-      exit 1
-    fi
-    ;;
-
-  *)
-    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
-    exit 1
-    ;;
-
-esac
-
-exit 0
+RETVAL=$?
+exit $RETVAL
