fix debian installer

diff --git a/flapjack-2.0.0/DEBIAN/postinst b/flapjack-2.0.0/DEBIAN/postinst
--- a/flapjack-2.0.0/DEBIAN/postinst
+++ b/flapjack-2.0.0/DEBIAN/postinst
@@ -13,82 +13,78 @@ INITDDIR="/etc/init.d"
 
 if [ "$1" = "configure" ]
 then
-if ! getent passwd flapjack > /dev/null
-then
-groupadd flapjack
-useradd --system --gid flapjack --no-create-home flapjack
-fi
+	if ! getent passwd flapjack > /dev/null
+	then
+		groupadd flapjack
+		useradd --system --gid flapjack --no-create-home flapjack
+	fi
 
-function error_exit
-{
-  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-  exit 1
-}
+	function error_exit
+	{
+		echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+		exit 1
+	}
 
-# Set up config + logging directories
-mkdir -p /etc/flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack/redis-flapjack
-chown -R flapjack:flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack
+	# Set up config + logging directories
+	mkdir -p /etc/flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack/redis-flapjack
+	chown -R flapjack:flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack
 
-# if [ ! -e /etc/flapjack/flapjack_config.toml ] ; then
-#   echo "Creating /etc/flapjack/flapjack_config.toml"
-#   cp ${FLAPJACK_GEM_DIR}/etc/flapjack_config.toml.example ${CONFIG_DIR}/flapjack_config.toml
-# fi
+	# if [ ! -e /etc/flapjack/flapjack_config.toml ] ; then
+	#   echo "Creating /etc/flapjack/flapjack_config.toml"
+	#   cp ${FLAPJACK_GEM_DIR}/etc/flapjack_config.toml.example ${CONFIG_DIR}/flapjack_config.toml
+	# fi
 
-# for version in 3 4 ; do
-#   if [ ! -e /usr/local/lib/flapjackfeeder${version}.o ] ; then
-#     echo "Creating /usr/local/lib/flapjackfeeder${version}.o for Nagios ${version}"
-#     cp ${FLAPJACK_GEM_DIR}/flapjackfeeder${version}.o /usr/local/lib/flapjackfeeder${version}.o
-#   fi
-# done
+	# for version in 3 4 ; do
+	#   if [ ! -e /usr/local/lib/flapjackfeeder${version}.o ] ; then
+	#     echo "Creating /usr/local/lib/flapjackfeeder${version}.o for Nagios ${version}"
+	#     cp ${FLAPJACK_GEM_DIR}/flapjackfeeder${version}.o /usr/local/lib/flapjackfeeder${version}.o
+	#   fi
+	# done
 
-if [ ! -e /usr/local/lib/flapjackfeeder.o ] ; then
-  echo "Symlinking the Nagios version 3 flapjackfeeder to /usr/local/lib/flapjackfeeder.o for backwards compatibility"
-  ln -s /usr/local/lib/flapjackfeeder3.o /usr/local/lib/flapjackfeeder.o
-fi
+	if [ ! -e /usr/local/lib/flapjackfeeder.o ] ; then
+		echo "Symlinking the Nagios version 3 flapjackfeeder to /usr/local/lib/flapjackfeeder.o for backwards compatibility"
+		ln -s /usr/local/lib/flapjackfeeder3.o /usr/local/lib/flapjackfeeder.o
+	fi
 
-#if [ ! -e ${INITDDIR}/redis-flapjack ] ; then
-#  echo "Creating ${INITDDIR}/redis-flapjack"
-#  chmod u+x ${INITDDIR}/redis-flapjack
-#fi
+	#if [ ! -e ${INITDDIR}/redis-flapjack ] ; then
+	#  echo "Creating ${INITDDIR}/redis-flapjack"
+	#  chmod u+x ${INITDDIR}/redis-flapjack
+	#fi
 
-if [ ! -e ${INITDDIR}/flapjack ] ; then
-  echo "Creating ${INITDDIR}/flapjack"
-  chmod u+x ${INITDDIR}/flapjack
-fi
+	if [ ! -e ${INITDDIR}/flapjack ] ; then
+		echo "Creating ${INITDDIR}/flapjack"
+		chmod u+x ${INITDDIR}/flapjack
+	fi
 
-if [ ! -e ${INITDDIR}/flapper ] ; then
-  echo "Creating ${INITDDIR}/flapper"
-  chmod u+x ${INITDDIR}/flapper
-fi
+	if [ ! -e ${INITDDIR}/flapper ] ; then
+		echo "Creating ${INITDDIR}/flapper"
+		chmod u+x ${INITDDIR}/flapper
+	fi
 
-# echo "Setting paths"
-if [ ! -e /etc/profile.d/flapjack.sh ] ; then
-  cat > /etc/profile.d/flapjack.sh <<'EOF'
-PATH=$PATH:/opt/flapjack/bin
-GEM_PATH=/opt/flapjack/vendor/bundle/ruby/*/
-EOF
-  chmod 644 /etc/profile.d/flapjack.sh
-fi
+	# echo "Setting paths"
+	if [ ! -e /etc/profile.d/flapjack.sh ] ; then
+		cat > /etc/profile.d/flapjack.sh <<'EOF'
+		PATH=$PATH:/opt/flapjack/bin
+		GEM_PATH=/opt/flapjack/vendor/bundle/ruby/*/
+		EOF
+		chmod 644 /etc/profile.d/flapjack.sh
+	fi
 
 
-update-rc.d redis-server defaults 94 06 >/dev/null || exit $?
-update-rc.d flapjack defaults 95 05 >/dev/null || exit $?
-# echo "Starting redis"
-if pidof redis-server >/dev/null; then
-        ${INITDDIR}/redis-server restart >/dev/null || exit $?
-else
-        ${INITDDIR}/redis-server start >/dev/null || exit $?
-fi
+	update-rc.d redis-server defaults 94 06 >/dev/null || exit $?
+	update-rc.d flapjack defaults 95 05 >/dev/null || exit $?
+	# echo "Starting redis"
+	if pidof redis-server >/dev/null; then
+		#dpkg-divert --package redis-server --local  --remove --rename /etc/redis/redis.conf.disabled
+		#dpkg-divert --divert /etc/redis/redis.conf.flapjack --rename /etc/redis/redis.conf
+		${INITDDIR}/redis-server restart >/dev/null || exit $?
+	else
+		${INITDDIR}/redis-server start >/dev/null || exit $?
+	fi
 
-# echo "Starting flapjack"
-${INITDDIR}/flapjack start || exit $?
+	# echo "Starting flapjack"
+	${INITDDIR}/flapjack start || exit $?
 
-echo "Thank you for installing flapjack!"
-echo
-echo "Log in again to have /opt/flapjack/bin added to your PATH or run:"
-echo "  export PATH=$PATH:/opt/flapjack/bin"
-echo
-
-echo "Flapjack should now be running. Visit http://localhost:3080/"
+	echo "Flapjack should now be running. Visit http://localhost:3080/"
 fi
 exit 0
